name:                DiskFS
version:             0.1.0.0
github:              "s-zeng/haskell-monads-showcase"
license:             AGPLv3
author:              "Simon Zeng"
maintainer:          "contact@simonzeng.com"
copyright:           "2021 Simon Zeng"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/s-zeng/haskell-monads-showcase#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers
- mtl

executables:
  diskfs-exe:
    main:                DiskFS.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -W
    - -Werror
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []
